clear;
clc;
fs=10;
N=990;
n=0:N-1;
t=n/fs;
A=1;
f=1;
y=A*cos(2*pi*f*t+pi/2);
subplot(3,1,1);
plot(t,y);
title('time-domain');
xlabel('TIME/(S)');ylabel('Amplituded');

Y=fft(y,N);
py2=(Y/N)*2;
mag=abs(py2);
f=(0:1000)*1000/1000;
subplot(3,1,2);
plot(mag);
title('Amplituded-frequence');
xlabel('frequence/(Hz)');ylabel('Amplituded');

py=angle(Y);
py=180/pi*py;
subplot(3,1,3);
plot(py);
title('phase-frequence');
xlabel('frequence/(Hz)');ylabel('phase');
